CMEK support changes
gardener/machine-controller-manager-provider-gcp pull request #84
Opened 2023-05-25 06:36 UTC by elankath

**What this PR does / why we need it**:
Changes required to support CMEK Encrypted disks in GCP.

**Which issue(s) this PR fixes**:
Fixes #78

**Special notes for your reviewer**:
tests  in progress.
**Release note**:

```improvement user
Support for CMEK Encrypted Disks as described in: https://github.com/gardener/gardener-extension-provider-gcp/issues/564
```

2023-05-25 08:39 UTC, ashwani2k commented
[celebrate]     Kumar, Ashwani reacted to your message:
________________________________
From: Tarun Ramakrishna Elankath ***@***.***>
Sent: Thursday, May 25, 2023 6:36:56 AM
To: gardener/machine-controller-manager-provider-gcp ***@***.***>
Cc: Kumar, Ashwani ***@***.***>; Review requested ***@***.***>
Subject: [gardener/machine-controller-manager-provider-gcp] CMEK support changes (PR #84)


What this PR does / why we need it:
Changes required to support CMEK Encrypted disks in GCP.

Which issue(s) this PR fixes:
Fixes #78<https://github.com/gardener/machine-controller-manager-provider-gcp/issues/78>

Special notes for your reviewer:
tests in progress.
Release note:

Support for CMEK Encrypted Disks as described in: https://github.com/gardener/gardener-extension-provider-gcp/issues/564


________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84

Commit Summary

  *   984b9e7<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84/commits/984b9e7d142d6ae0e0cd2f659b8ae4725b6d1755> CMEK support changes

File Changes

(5 files<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84/files>)

  *   M pkg/api/v1alpha1/provider_spec.go<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84/files#diff-bd1b247473fbbde507d51db370b78fb10ed9413acde9f98c73e290eaf2bfee2a> (9)
  *   M pkg/gcp/machine_controller.go<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84/files#diff-c529338f56b2f91e80e0fdd2962629f1f69b94d0ac9f7faef21c5791ce7a9b01> (17)
  *   M pkg/gcp/machine_controller_test.go<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84/files#diff-0219be6431bf8e562f7356c75d8dbeba1f0afcb18f5abfa2243cc4d2b406995f> (150)
  *   M pkg/gcp/machine_controller_util.go<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84/files#diff-37cdf41d20d791270632d63f8e818d3215cb2ce332bf16c837f3f83d3e1b0f8f> (14)
  *   M pkg/gcp/validation/validation.go<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84/files#diff-4317df83b48e3723adc9d01622dddff54d3074a2056e258b3ac9a07e41055fb4> (9)

Patch Links:

  *   https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84.patch
  *   https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84.diff

—
Reply to this email directly, view it on GitHub<https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAF5XNR2XKSK7C7QB2FULNTXH34YRANCNFSM6AAAAAAYOLYVCY>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2023-05-25 09:08 UTC, elankath commented
# HOW TO MANUALLY TEST FEATURE 
1. Setup a GCP shoot cluster using a service account
1. Setup Cloud KMS Key and Assign IAM role:
    1. Install gcloud CLI: `brew install gcloud`
    1. Login into gcloud: `gcloud auth login`
    1. Create a Cloud KMS keyring: `gcloud kms keyrings create cmektest --location=us-east4`. (This requires IAM privileges to be assigned to you)
    1. Create a Cloud KMS Key for encryption purpose: `gcloud kms keys create alpha --keyring=cmektest --location=us-east4 --purpose encryption`
    1. List to get fully qualified path of Cloud KMS Key: 
    ```
    gcloud kms keys list --keyring=cmektest --location=us-east4
    NAME                                                                                                                                                       PURPOSE
    projects/projectId/locations/us-east4/keyRings/cmektest/cryptoKeys/alpha    ENCRYPT_DECRYPT
    ```
    1. Give the service account used to create the shoot cluster relevant IAM role to use this key
    ```
    gcloud projects add-iam-policy-binding projectId --member serviceAccount:user@projectId.iam.gserviceaccount.com --role roles/cloudkms.cryptoKeyEncrypterDecrypter
    ```
1. Checkout the `machine-controller-manager` and `machine-controller-manager-provider-gcp` in peer directories under `$GOPATH/src/github.com/gardener`.
3. Setup and Start Local MCM: 
     1. `cd $GOPATH/src/github.com/gardener/machine-controller-manager`
     2. `make download-kubeconfigs`
     4. `make start 2>&1 | tee /tmp/mcm.log`
5. Start Local MC 
     1. `cd $GOPATH/src/github.com/gardener/machine-controller-manager-provider-gcp`
     2. `make start 2>&1 | tee /tmp/mcm-gcp.log`
     3. Wait for any pending reconciles to finish.
6. Edit the `MachineClass` yaml
     1. `k edit mcc`
     2.   Modify `providerSpec.disks` as follows: adding `kmsKeyName` and `kmsKeyServiceAccount` as illustrated below (example below makes boot disk CMEK encrypted):
     ```yaml
          - autoDelete: true
             boot: true
             kmsKeyName: projects/projectId/locations/us-east4/keyRings/cmektest/cryptoKeys/alpha
             kmsKeyServiceAccount: user@projectId.iam.gserviceaccount.com
      ```
7.  Trigger restart of `Machine`
      1. List the existing `Running` machine:
       ```
      k get machine
      shoot--userid--shootName-worker-alpha-z1-9485d-xprld
       ```
    1. Add the `force-deletion` label to the machine. (So restart is faster)
        ```
           k label mc shoot--userid--shootName-worker-alpha-z1-9485d-xprld force-deletion=true
        ```
     1. Delete the machine: `k delete mc shoot--userid--shootName-worker-alpha-z1-9485d-xprld`
     1. Wait for reconcile to finish and confirm new machine is `Running`
       ```
       k get machine                                    
       NAME                                                        STATUS    AGE   
       shoot--userid--shootName-worker-alpha-z1-9485d-96fkl   Running   67m   
       ```
 11. Confirm Disk Creation/Encryption.
       1. Test to see that corresponding boot disk is created via gcloud CLI. (The boot disk name is same as machine name)
          ```
             gcloud compute disks list | grep 96fkl
             shoot--userid---shootName-worker-alpha-z1-9485d-96fkl  us-east4-c      zone            50       pd-balanced  READY
           ```
       1. Confirm that disk is using CMEK encryption key:
       ```
           gcloud compute disks describe shoot--shootName-worker-alpha-z1-9485d-96fkl --zone us-east4-c worker-alpha-z1-9485d-96fkl --zone us-east4-c
           creationTimestamp: '2023-05-25T00:46:41.136-07:00'
           diskEncryptionKey:
               kmsKeyName: projects/projectId/locations/us-east4/keyRings/cmektest/cryptoKeys/alpha/cryptoKeyVersions/2
               kmsKeyServiceAccount: user@projectId.iam.gserviceaccount.com
            id: '843731016874110129'
       ```

2023-05-25 10:43 UTC, kon-angelo approved these changes
/lgtm

2023-05-25 12:55 UTC, elankath commented
Review comments from meeting:
1. Support empty `kmsKeyServiceAccount`  that defaults to compute engine service agent account. (Google's doc is WRONG here)
2. Move keys to separate `GCPDiskEncryption` struct.

2023-05-26 03:39 UTC, ashwani2k commented
A suggestion, shall we move the How to test manually from the https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84#issuecomment-1562553340 to the docs instead as I believe this will be handy later as well.  wdyt?

/hold because of https://github.com/gardener/machine-controller-manager-provider-gcp/pull/84#issuecomment-1562859544

2023-05-26 03:42 UTC, elankath commented
Yes, will be moving this inside the `docs` and updating with tests, refactoring.

2023-05-26 03:54 UTC, unmarshall reviewed
Minor comments

2023-05-26 03:54 UTC, unmarshall commented on pkg/gcp/machine_controller_util.go
> +		if disk.KmsKeyName != "" {
is there a possibility that someone provides only spaces as the keyName? Safe thing to do would be to just trim `disk.KmsKeyName`

2023-05-26 03:54 UTC, unmarshall commented on pkg/gcp/validation/validation.go
> +		if disk.KmsKeyName != "" && disk.KmsKeyServiceAccount == "" {
same as above and this time for both `KmsKeyName` and `KmsKeyServiceAccount` as well.

2023-05-26 03:54 UTC, unmarshall reviewed
Minor comments

2023-05-26 04:55 UTC, ashwani2k commented on pkg/gcp/machine_controller_test.go
> +	FailAtSpecValidationNoKmsKeyName        string = "machine codes error: code = [Internal] message = [Create machine \"dummy-machine\" failed on decodeProviderSpecAndSecret: machine codes error: code
Minor nit pick. 
```suggestion
	// FailAtSpecValidationNoKmsServiceAccount if kmsKeyName is specified but kmsKeyServiceAccount is missing
	FailAtSpecValidationNoKmsServiceAccount string = "machine codes error: code = [Internal] message = [Create machine \"dummy-machine\" failed on decodeProviderSpecAndSecret: machine codes error: code = [Internal] message = [Error while validating ProviderSpec [spec.disks[0].kmsKeyServiceAccount: Required value: kmsKeyServiceAccount is required to be specified along with kmsKeyName]]]"
	// FailAtSpecValidationNoKmsName if kmsKeyServiceAccount is specified but kmsKeyName is missing
	FailAtSpecValidationNoKmsKeyName        string = "machine codes error: code = [Internal] message = [Create machine \"dummy-machine\" failed on decodeProviderSpecAndSecret: machine codes error: code = [Internal] message = [Error while validating ProviderSpec [spec.disks[0].kmsKeyServiceAccount: Required value: kmsKeyName is required to be specified along with kmsKeyServiceAccount]]]"
```

2023-05-26 05:19 UTC, ashwani2k commented on pkg/gcp/machine_controller_test.go
> +	FailAtSpecValidationNoKmsKeyName        string = "machine codes error: code = [Internal] message = [Create machine \"dummy-machine\" failed on decodeProviderSpecAndSecret: machine codes error: code
Just for completeness sake that it caught your eye as well, as I saw the commit mentions `Error message grammar`. 
The Lines 74/75 in the original were duplicated without any change to text and were also placed wrongly.

2023-06-01 07:09 UTC, himanshu-kun requested changes
kindly update the file https://github.com/gardener/machine-controller-manager-provider-gcp/blob/15502b8d9a3b50251e250048ccb95cdffdc3c600/kubernetes/machine-class.yaml#L11-L18, and keep the `encryption` section commented (to specify its optional)

Kindly also write `# optional` for `kmsKeyServiceAccount` field  (like done [here](https://github.com/gardener/machine-controller-manager-provider-equinix-metal/blob/a42baed0635e3f73a786d122fca6d7486e255ade/kubernetes/machine-class.yaml#L18))

2023-06-01 07:09 UTC, himanshu-kun commented on pkg/gcp/validation/validation.go
> +			}
this is the case where customer provides spaces , right?
```suggestion
// to deal with situation where  just spaces have been specified for `kmsKeyServiceAccount`
			if disk.Encryption.KmsKeyServiceAccount != "" && kmsKeyServiceAccount == "" {
				allErrs = append(allErrs, field.Required(idxPath.Child("kmsKeyServiceAccount"), "kmsKeyServiceAccount should either be explicitly specified without spaces or left un-specified to default to the Compute Service Agent"))
			}
```

2023-06-01 07:40 UTC, elankath commented on pkg/gcp/machine_controller_util.go
> +				attachedDisk.DiskEncryptionKey.KmsKeyName, attachedDisk.DiskEncryptionKey.KmsKeyServiceAccount)
Ok, it now appears like this in log 
```
I0601 13:09:30.853523   99845 machine_controller_util.go:131] (CreateMachineUtil) For machineName: "shoot--i034796--tre-gcp-alpha-worker-alpha-z1-5bb75-6lvtq", diskLabel: "tre-gcp-alpha", DiskEncryptionKey.KmsKeyName: "projects/sap-se-gcp-k8s-dev-team/locations/us-east4/keyRings/cmektest/cryptoKeys/alpha", DiskEncryptionKey.KmsKeyServiceAccount: "elkat1@sap-se-gcp-k8s-dev-team.iam.gserviceaccount.com"
```

2023-06-01 09:05 UTC, himanshu-kun approved these changes
/lgtm

2023-06-01 09:14 UTC, merged